package com.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-12T11:02:20.220+08:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://service.com/", name = "WebServiceSample")
public interface WebServiceSample {

    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public String say(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );
}
