package com.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-12T11:02:20.228+08:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "WebServiceSampleImplService", 
                  wsdlLocation = "http://localhost:8080/services/WebServiceSample?wsdl",
                  targetNamespace = "http://impl.service.com/") 
public class WebServiceSampleImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.com/", "WebServiceSampleImplService");
    public final static QName WebServiceSampleImplPort = new QName("http://impl.service.com/", "WebServiceSampleImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/WebServiceSample?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServiceSampleImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/services/WebServiceSample?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServiceSampleImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServiceSampleImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceSampleImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WebServiceSample
     */
    @WebEndpoint(name = "WebServiceSampleImplPort")
    public WebServiceSample getWebServiceSampleImplPort() {
        return super.getPort(WebServiceSampleImplPort, WebServiceSample.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceSample
     */
    @WebEndpoint(name = "WebServiceSampleImplPort")
    public WebServiceSample getWebServiceSampleImplPort(WebServiceFeature... features) {
        return super.getPort(WebServiceSampleImplPort, WebServiceSample.class, features);
    }

}
